### ISSUE TITLE
Luet feature issue tracker

### ISSUE THREAD

**Issue by mudler** [mocaccinoOS/issue-tracker#8]
Creating this issue to collect features that we need from luet and have priority for a 0.x release:

Usability:
- [ ] [Create wrapper to mimick equo commands](https://github.com/mudler/luet/issues/85)
- [ ]  [Add user prompts](https://github.com/mudler/luet/issues/106)
- [ ]  [Add show-tree command for a package](https://github.com/mudler/luet/issues/23)

Feature-wide:
- [ ]  [Feature: luet database](https://github.com/mudler/luet/issues/47)
- [ ]  [Special label to warn user after install](https://github.com/mudler/luet/issues/99)
- [ ]  [Package locking/pinning](https://github.com/mudler/luet/issues/101)

Migration:
- [ ]  [Optimize 'reclaim' ](https://github.com/mudler/luet/issues/115)

Wanted, but not necessary:
- [ ] [Add zstd support](https://github.com/mudler/luet/issues/97)

Whoever fixes them, gets a :beers: !

**Comment by geaaru** [comment]
Luet zstd integration added with https://github.com/mudler/luet/commit/f0fae82ad9f74331dfef206c293552e2bb17c891
